### ISSUE TITLE
2.4: Select Contact Spacing

### ISSUE THREAD

**Issue by beaglesnuf** [jff99/KeyCip#4]
[Spacing for 'Select a contact'](https://i.ibb.co/9cLm35c/keycip-select-contact.png) could be improved. Currently, there is very little room for error when choosing contacts due to minimal spacing in between contacts. Also, is there a reason why 'Select a contact' is listed twice (top and bottom) in the UI?

**Comment by jff99** [comment]
Fist of all, thanks for posting a new Issue and contributing to the project. The spacing should be solved in the latest version (v2.5). The reason why 'Select contact' is listed twice is because it serves as a flag in order to find out whether the user has selected a contact or not (also it gives you a clue what you are supposed to do)
