### ISSUE TITLE
navigation/status bar color

### ISSUE THREAD

**Issue by andsofine** [jff99/KeyCip#5]
change navigation/status bar color to background color for dark/light theme
![AFFIX_20220702_182433.png](https://user-images.githubusercontent.com/99369164/177006937-6b58b972-39ba-4b29-b152-b963f46717da.png)

**Comment by jff99** [comment]
Hi, thanks for suggesting this improvement. It should be fixed in 2.5.1 version. Actually, it was solved half an hour after you posted the issue (but Google processing time is desperate).

Just out of curiosity, where do you download the application? Google Play? Directly from Github? Or through Fdroid?

**Comment by andsofine** [comment]
great job

f-droid

**Comment by serrq** [comment]
I downloaded your app from F-droid too (Izzy repo).
